language: node_js

node_js:
  - 'node'
  - 'lts/*'

deploy:
  provider: heroku
  app: "funbox-test-uz"
  api_key:
    secure: "57e020ff-0c31-48b2-9e85-49eae6b8f8fb"

script:
  - npm test -- --maxWorkers=4
  - npm run build

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

