language: node_js

node_js:
  - 'node'
  - 'lts/*'

script:
  - npm test -- --maxWorkers=4
  - npm run build

  deploy:
  provider: heroku
  app: "funbox-test-uz"
  api_key:
    secure: "abb871c6-2649-404f-be9e-6bf05b25c0d3"


before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

